version: 2.0
jobs:
  build:
    working_directory: ~/v9
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: yarn
          command: 'yarn'
      - run:
          name: yarn-build
          command: 'yarn build'
      - run:
          name: npm-add-eslint
          command: 'sudo npm install -g eslint'
      - run:
          name: eslint
          command: "eslint --max-warnings 0 './src/**/*.js'"
